services:
  - type: web
    name: wanderlust
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node app.js
    autoDeploy: true

    envVars:
      - key: NODE_ENV
        value: production
      

       -key: PORT
        value: 3000

      - key: ATLAS_URL
        sync: false

      - key: CLOUD_NAME
        sync: false

      - key: CLOUDAPI_KEY
        sync: false

      - key: CLOUDAPI_SECRET
        sync: false

      - key: MAP_TOKEN
        sync: false